spring.application.name=stockflow-api

spring.datasource.url=jdbc:postgresql://ep-small-truth-acczc5bl-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_vtYWzyqfxZ58

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true

logging.level.org.hibernate.SQL=OFF

logging.level.org.hibernate.orm.jdbc.bind=OFF